openapi: 3.0.3
info:
  title: Access Control API
  version: 1.0.0
  description: API ...
  contact:
    name: ИУ9

servers:
  - url: https://sets.mgtu.ru/api/app/v1
    description: development server

tags:
  - name: image
    description: Операции для работы с изображениями.

paths:
  /image/{imageId}/info:
    parameters:
      - name: imageId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - image
      operationId: getImageInfo
      summary: Получение данных по изображению.
      description: Получение данных по изображению.
      responses:
        '200':
          description: Успешный ответ.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetImageInfoResponse"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /image/{imageId}:
    get:
      tags:
        - image
      operationId: getImage
      summary: Получение изображения.
      description: Получение изображения.
      parameters:
        - name: imageId
          in: path
          description: Идентификатор изображения, которое нужно получить.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: success
          content:
            multipart/formData:
              schema:
                $ref: "#/components/schemas/GetImageResponse"
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /image:
    post:
      tags:
        - image
      operationId: createImage
      summary: Создание изображения.
      description: Сохраняет снимок текущей обстановки.
      responses:
        '200':
          description: success
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      tags:
        - image
      operationId: getLastImage
      summary: Получение последнего изображения.
      description: Получение последнего изображения.
      responses:
        '200':
          description: success
          content:
            multipart/formData:
              schema:
                $ref: "#/components/schemas/GetImageResponse"
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
        details:
          type: string

    GetImageInfoResponse:
      type: object
      required:
        - id
        - created_at
        - people_number
      properties:
        id:
          type: string
          description: Уникальный идентификатор изображения.
          format: uuid
        created_at:
          type: string
          format: date-time
        people_number:
          type: integer
          minimum: 0

    GetImageResponse:
      description: Ответ на запрос получения изображения.
      type: string
      format: binary